import { MODULES, calcProgress, formatDate } from './ticketUtils';

export function buildMarkdown(ticket) {
  const { total, selected, percent } = calcProgress(ticket);
  const modules = MODULES.filter((m) => ticket.selectedModules.includes(m.id));
  const lines = [];

  lines.push(`# QA Test Manifest — ${ticket.ticketId || 'Untitled'}`);
  lines.push('');
  lines.push(`**Ticket title:** ${ticket.ticketTitle || '—'}  `);
  lines.push(`**Tester:** ${ticket.testerName || '—'}  `);
  lines.push(`**Modules covered:** ${modules.map((m) => m.name).join(', ') || '—'}  `);
  lines.push(`**Progress:** ${selected}/${total} items selected (${percent}%)  `);
  lines.push(`**Created:** ${formatDate(ticket.createdAt)}  `);
  lines.push(`**Last updated:** ${formatDate(ticket.updatedAt)}  `);
  lines.push('');
  lines.push('---');
  lines.push('');

  modules.forEach((mod) => {
    lines.push(`## ${mod.name}`);
    lines.push('');
    mod.categories.forEach((cat) => {
      const relevantItems = cat.items.filter((it) => ticket.itemStates?.[it.id]?.selected);
      if (relevantItems.length === 0) return;
      lines.push(`### ${cat.name}`);
      lines.push('');
      relevantItems.forEach((item) => {
        const state = ticket.itemStates?.[item.id] || {};
        lines.push(`- [x] ${item.text}`);
        if (state.remark && state.remark.trim()) {
          lines.push(`  - **Remark:** ${state.remark.trim()}`);
        }
      });
      lines.push('');
    });
  });

  lines.push('---');
  lines.push('');
  lines.push('## Overall Remarks');
  lines.push('');
  lines.push(ticket.overallRemarks?.trim() ? ticket.overallRemarks.trim() : '_No overall remarks provided._');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by QA Manifest on ${formatDate(new Date().toISOString())}*`);

  return lines.join('\n');
}

export function downloadMarkdown(ticket) {
  const md = buildMarkdown(ticket);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(ticket.ticketId || 'qa-checklist').replace(/[^a-z0-9-_]+/gi, '_')}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
